#!/bin/bash

export NS3_HOME="$HOME/ns3-dce"
cd $NS3_HOME/source/ns-3-dce
./waf configure --with-ns3=$NS3_HOME/build --prefix=$NS3_HOME/build --enable-kernel-stack=$NS3_HOME/source/net-next-sim-2.6.36/arch
